language: ruby
rvm:
  - 2.4.0
before_script:
  - "nvm install 7.8.0"
  - "nvm use 7.8.0"
  - "npm install -g yarn"
  - "yarn"
  - "bundle exec rake db:drop db:create db:migrate"
script:
  - "npm test"
  - "bundle exec rspec spec/"
